[parity]
chain = "./demo-spec.json"
base_path = "./node0"
[network]
port = 30300
reserved_peers = "./nodes.address"
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8183
[websockets]
port = 8450
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "none"
usd_per_tx = "0"
