[parity]
chain = "./demo-spec.json"
base_path = "./node2"
[network]
port = 30302
reserved_peers = "./nodes.address"
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8182
[websockets]
port = 8452
